export const projects = [
  {
    title: 'Chatty',
    description: "A chat application which is an improvement of sogecord. This chat application has login system with google or facebook, custom rooms, removing members (this function is aviable for room creators only), attaching files and much more! Note: this app is a bit glitchy.",
    image: '/images/chatty.JPG',
    tags: ['FireBase', 'ReactJs', 'JavaScript'],
    source: 'https://github.com/HendsomDoge/chatty',
    visit: 'https://sogechat.netlify.app/',
    id: 5,
  },
  {
    title: 'Travel Advisor',
    description: "A travel advisor app with a built in map which has almost all of the restaurants, hotels and attractions. You can search for places and even choose filters. This app also has a rating system and it also displays its leaderboard rank.",
    image: '/images/travel.JPG',
    tags: ['ReactJs', 'JavaScript', 'CSS'],
    source: 'https://github.com/HendsomDoge/travelAdvisor',
    visit: 'https://traveladviser.netlify.app/',
    id: 4,
  },
  {
    title: 'SogeVid Chat App',
    description: "I have built a video chat application in which two users can communicate with each other through voice and videos. This has an id system which you can share using SogeCord (or any place where u can share things) and the user has to put the id and call the other user. This is one of my most recent projects.",
      image: '/images/sogevid.JPG',
      tags: ['WebRTC', 'Socket.io', 'React.js', 'Node.js'],
    source: 'https://github.com/HendsomDoge/sogevid',
    visit: 'https://sogevid.netlify.com',
    id: 3,
  },
  {
    title: 'SogeCord',
    description:"My first major application called SogeCord. This is a chat application which has rooms and multiple users can communicate with each other. This is a very basic chat application so there aren't really that much features and it is released publicy",
    image: '/images/1.png',
    tags: ['JavaScript', 'Socket.io', 'Node.js'],
    source: '#',
    visit: 'https://sogecord-2.herokuapp.com',
    id: 2,
  },
  {
    title: 'Hendsom Bot',
    description: "Hendsom Bot, this is a discord bot made by me which has many features such as moderation, music, level up, welcoming and much more! This bot constantly gets updates and new command and what's more is that all of the commands are completely free! If you want to invite the bot to your server then just click the \"Visit\" button below.",
      image: '/images/3.png',
      tags: ['JavaScript', 'Aoi.js', 'Node.js'],
    source: 'https://youtu.be/dQw4w9WgXcQ',
    visit: 'https://dsc.gg/hendsombot',
    id: 1,
  },
  {
    title: 'Covid Tracker',
    description: "A Covid Tracker built by me which has country selection, global reports, global leaderboard, bar charts along with a dark mode and light mode switch. There is a problem with the api so recovered does not work.",
    image: '/images/4.jpg',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/HendsomDoge/covidTracker2',
    visit: 'https://hendsomdoge.github.io/covidTracker2/',
    id: 0,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started learning javascript', },
  { year: 2021, text: 'Started Leaning HTML/CSS and react native', },
  { year: 2021, text: 'Started learning python', },
  { year: 2021, text: 'Started developing projects', },
];