export const projects = [
  {
    title: 'Hendsom Bot',
    description: "Hendsom Bot, this is a discord bot made by me which has many features such as moderation, music, level up, welcoming and much more! This bot constantly gets updates and new command and what's more is that all of the commands are completely free! If you want to invite the bot to your server then just click the \"Visit\" button below. This is by far the biggest project I ever made.",
      image: '/images/3.png',
      tags: ['JavaScript', 'Aoi.js', 'Node.js'],
    source: '#  ',
    visit: 'https://hendsombot.netlify.app/',
    id: 11,
  },
  {
    title: 'Sussy Video Calling App',
    description: "Sussy Video Calling App (Calling SVCA for Short) is a lot of imporovement to sogevid. It has host controls, muting audio & video, screen sharing, view changing and much more!",
      image: '/images/viddy.JPG',
      tags: ['JavaScript', 'React', 'Node.js'],
    source: '#',
    visit: 'https://sussyvidchat.netlify.app',
    id: 10,
  },
  {
    title: 'SogeChat',
    description: "SogeChat is an Overall Improvement of SogeCord, it has images, dms group chats and much more. This app is a little buggy tho.",
      image: '/images/sogechat.JPG',
      tags: ['JavaScript', 'React', 'Node.js'],
    source: 'https://github.com/HendsomDoge/chatty',
    visit: 'https://sogechat.netlify.app/',
    id: 9,
  },
  {
    title: 'CryptoSus',
    description: "This is a sussy cryptocurrency tracker with information such as ost popular currencies, information on single currencies, news etc.",
      image: '/images/cri.JPG',
      tags: ['JavaScript', 'Nodejs', 'Reactjs', 'HTML/CSS'],
    source: 'https://youtu.be/dQw4w9WgXcQ',
    visit: 'https://cryptosus.netlify.app',
    id: 8,
  },
  {
    title: 'Sussy Image Yes',
    description: "This is an online image gallery where you can share images with your friends",
      image: '/images/drip.PNG',
      tags: ['JavaScript', 'Nodejs', 'Reactjs', 'HTML/CSS'],
    source: 'https://youtu.be/dQw4w9WgXcQ',
    visit: 'https://sussypicious.netlify.app/',
    id: 7,
  },
  {
    title: 'Sussy Web Store',
    description: "This is a web store which does NOT actually deliver products. In, this webstore, you have a cart system and you can also do payments. I could also app other functionalities such as emailing me who purchased the order and emailing the person about order details but I needed to add my credit card for that which I'm unable to do.",
    image: '/images/pwa.JPG',
    tags: ['ReactJs', 'JavaScript', 'Nodejs', 'Stripe'],
    source: 'https://github.com/HendsomDoge/sussywebstore',
    visit: 'https://sussywebstore.netlify.app/',
    id: 6,
  },
  {
    title: 'Sussy Expense Tracker',
    description: "This is a expense tracker which keeps a track of your expenses and incomes with the help of charts. What's more is that you can also use this app through voice by simply holding down the space bar.",
    image: '/images/sussyet.JPG',
    tags: ['ReactJs', 'JavaScript'],
    source: 'https://github.com/HendsomDoge/sussyexpensetracker',
    visit: 'https://sussyexpensetracker.netlify.app/',
    id: 5,
  },
  {
    title: 'SogeBook',
    description: "A social media application which has many features such as posting, commenting on posts, liking posts, editing posts, deleting posts, searching for posts (with tags or title/description) and login features. This is by far the biggest web application project I ever.",
    image: '/images/chatty.JPG',
    tags: ['MongoDB', 'ReactJs', 'JavaScript'],
    source: 'https://github.com/HendsomDoge/sogebook',
    visit: 'https://sogechat.netlify.app/',
    id: 4,
  },
  {
    title: 'Travel Advisor',
    description: "A travel advisor app with a built in map which has almost all of the restaurants, hotels and attractions. You can search for places and even choose filters. This app also has a rating system and it also displays its leaderboard rank.",
    image: '/images/travel.JPG',
    tags: ['ReactJs', 'JavaScript', 'CSS'],
    source: 'https://github.com/HendsomDoge/travelAdvisor',
    visit: 'https://traveladviser.netlify.app/',
    id: 3,
  },
  {
    title: 'SogeVid Chat App',
    description: "I have built a video chat application in which two users can communicate with each other through voice and videos. This has an id system which you can share using SogeCord (or any place where u can share things) and the user has to put the id and call the other user",
      image: '/images/sogevid.JPG',
      tags: ['WebRTC', 'Socket.io', 'React.js', 'Node.js'],
    source: 'https://github.com/HendsomDoge/sogevid',
    visit: 'https://sogevid.netlify.com',
    id: 2,
  },
  {
    title: 'SogeCord',
    description:"My first major application called SogeCord. This is a chat application which has rooms and multiple users can communicate with each other. This is a very basic chat application so there aren't really that much features and it is released publicy",
    image: '/images/1.png',
    tags: ['JavaScript', 'Socket.io', 'Node.js'],
    source: '#',
    visit: 'https://sogecord-2.herokuapp.com',
    id: 1,
  },
  {
    title: 'Covid Tracker',
    description: "A Covid Tracker built by me which has country selection, global reports, global leaderboard, bar charts along with a dark mode and light mode switch. There is a problem with the api so recovered does not work.",
    image: '/images/4.jpg',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/HendsomDoge/covidTracker2',
    visit: 'https://hendsomdoge.github.io/covidTracker2/',
    id: 0,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started learning javascript', },
  { year: 2021, text: 'Started Leaning HTML/CSS and react native', },
  { year: 2021, text: 'Started learning python', },
  { year: 2021, text: 'Started developing projects', },
];